### ISSUE TITLE
Improve documentation on when custom onfiguration of indexing is necessary

### ISSUE THREAD

**Issue by dimaip** [Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor#126]
Currently to enable sorting by date (or by any other property as well?), one must configure the relevant property with this config in NodeTypes.yaml:

```
      search:
        elasticSearchMapping:
          type: date
          include_in_all: false
          format: 'date_time_no_millis'
        indexing: '${(value ? Date.format(value, "Y-m-d\TH:i:sP") : null)}'
```

But the docs say: `Normally, this does not need to be touched, as this package supports all Neos data types natively.`

Can somebody who's into the subject clarify, under what circumstances must one configure the `indexing` config?
