### ISSUE TITLE
Type error in in "Objects.yaml"-configuration

### ISSUE THREAD

**Issue by dnepro** [Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor#158]
On running the "flow configuration:validate"-command i receive an error, for the `Flowpack\ElasticSearch\ContentRepositoryAdaptor\Command\NodeIndexCommandController`-configuration in the Objects.yaml, stating that it expected a string but got an array:
```yaml
- Objects.Flowpack.ElasticSearch.ContentRepositoryAdaptor.Flowpack\ElasticSearch\ContentRepositoryAdaptor\LoggerInterface.arguments.__index_3.value -> expected: type=string found: type=array
``` 

and in deed the code looks like this: 
```yaml
Flowpack\ElasticSearch\ContentRepositoryAdaptor\Command\NodeIndexCommandController:
  properties:
    logger:
      object:
        factoryObjectName: TYPO3\Flow\Log\LoggerFactory
        factoryMethodName: create
        arguments:
          3:
            value:
              fileBackend: 'TYPO3\Flow\Log\Backend\FileBackend'
              ansiConsoleBackend: 'TYPO3\Flow\Log\Backend\AnsiConsoleBackend'
```

I don't know whether this is actually correct and the "flow configuration:validate"-command is wrong.
