### ISSUE TITLE
Use flattened field type instead of object for neos_fulltext_parts

### ISSUE THREAD

**Issue by daniellienert** [Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor#356]
The field neos_fulltext_parts stores the fulltext path for every aggregateRoot document with the childnode identifiers as keys. This easily can lead to mapping explosion. Starting with Elasticsearch 7.x, you can configure:

```
  properties:
    'neos_fulltext_parts':
      search:
        elasticSearchMapping:
          type: flattened
        indexing: ''
```

to avoid this. 
This should be the default when 7.x is the minimal supported version.

**Comment by kdambekalns** [comment]
The bad thing is, we can#t simply override this in userland code… The default is

```
    'neos_fulltext_parts':
      search:
        elasticSearchMapping:
          type: object
          enabled: false
        indexing: ''
```

and when changing the type to `flattened`, you get this: `Mapping definition for [neos_fulltext_parts] has unsupported parameters:  [enabled : false]`

**Comment by kdambekalns** [comment]
I changed this directly, `configuration:show` now gives me:

```
        neos_fulltext_parts:
            search:
                elasticSearchMapping:
                    type: flattened
                indexing: ''
```

like above. I still get this:

```
{
    "update": {
        "_index": "neos-fb11fdde869d0a8fcfe00a2fd35c031d",
        "_type": "_doc",
        "_id": "0c079d7c6c2a427f76eaf55340dd28d79ce3ae47",
        "status": 400,
        "error": {
            "type": "illegal_argument_exception",
            "reason": "Limit of total fields [1000] has been exceeded"
        }
    }
}
```
Debugging shows me: During indexing, an index named like `neos-e781f29c8dd927c09735547a848e3459-1612469847` is created, that shows this when fetching the mapping:

```
"neos_fulltext_parts": {
	"type": "flattened"
}
```

As soon as documents are actually added, this happens to an index named like `neos-e781f29c8dd927c09735547a848e3459` (note the missing suffix), in which the mapping is like this:

```
"neos_fulltext_parts": {
	"properties": {
		"04b90b2e-fc62-4c31-aa7a-12cbb2c8dc94": {
			"properties": { … }
		},
		…
	}
}
```
