### ISSUE TITLE
Elasticsearch 7.x mappings missing

### ISSUE THREAD

**Issue by rolandschuetz** [Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor#366]
Version 7 and 8 of this package support Elasticssearch 7, so I would expect the following configuration to work:
```
Flowpack:
  ElasticSearch:
    ContentRepositoryAdaptor:
      driver:
        version: 7.x
```

It seems that Elasticsearch 6 and 7 mapping is the same, so a mapping for 7.x should be added here:
https://github.com/Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor/blob/master/Configuration/Settings.yaml#L15
