### ISSUE TITLE
Explosion of mapping fields

### ISSUE THREAD

**Issue by DrillSergeant** [Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor#375]
Since version 7.0.5 elasticsearch field mapping for neos_fulltext_parts gets flooded:

```
                "neos_fulltext_parts": {
                    "properties": {
                        "01b4f10b-c7f8-4e37-9c0a-2e04bca0df54": {
                            "properties": {
                                "h1": {
                                    "type": "text",
                                    "fields": {
                                        "keyword": {
                                            "type": "keyword",
                                            "ignore_above": 256
                                        }
                                    }
                                }
                            }
                        },
                        "02d557fc-887b-4d79-bde5-5d5db6f0eaad": {
                            "properties": {
                                "h2": {
                                    "type": "text",
                                    "fields": {
                                        "keyword": {
                                            "type": "keyword",
                                            "ignore_above": 256
                                        }
                                    }
                                },
                 [this repeats for every existing node as far as I can see, lots of entries here]
```

This leads to this error during indexing:
 ```
 Error:
=======

{
    "update": {
        "_index": "neoscr-fb11fdde869d0a8fcfe00a2fd35c031d-1614847774",
        "_type": "_doc",
        "_id": "3eddf8a0b104c5169e09a18a040916e27d60078a",
        "status": 400,
        "error": {
            "type": "illegal_argument_exception",
            "reason": "Limit of total fields [1000] in index [neoscr-fb11fdde869d0a8fcfe00a2fd35c031d-1614847774] has been exceeded"
        }
    }
```

Reason for this is: the introduced array_filter here: https://github.com/Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor/compare/7.0.4...7.0.5#diff-433af2c73384cf274bd3eb5a72387db03cc0816ba92b69e59d14d1bd71464592R76

That filters all array-values that are boolean false out of the mapping-config, but for the field "neos_fulltext_parts" the config "enabled: false" is configured and I think it should not be filtered out.

```
'Neos.Neos:Document':
  search:
    fulltext:
      isRoot: true
  properties:
[...]
      search:
        elasticSearchMapping:
          type: object
          enabled: false
        indexing: ''
 ```

**Comment by kdambekalns** [comment]
Would be solved with https://github.com/Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor/issues/356, but since that is a bit tricky to do cross-version compatible, the easiest way is to change the settings if affected. Just add this to your nodetypes configuration in some way:

```yaml
'Neos.Neos:Document':
  properties:
    'neos_fulltext_parts':
      search:
        elasticSearchMapping:
          type: flattened
```

This needs at least `flowpack/elasticsearch-contentrepositoryadaptor` [v7.0.5](https://github.com/Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor/releases/tag/7.0.5) (to have https://github.com/Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor/pull/372)
