### ISSUE TITLE
during indexing, we use the NodeData's workspace name from time to time instead of the context

### ISSUE THREAD

**Issue by skurfuerst** [Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor#46]
For instance, see the following code:

```
protected function updateFulltext(Node $node, array $fulltextIndexOfNode, $targetWorkspaceName = NULL) {
        if ((($targetWorkspaceName !== NULL && $targetWorkspaceName !== 'live') || $node->getWorkspace()->getName() !== 'live') || count($fulltextIndexOfNode) === 0) {
            return;
        }

```

Here, we use $node->getWorkspace(), returning the workspace of the _UNDERLYING_ node data. which I think is wrong -- instead, $node->getContext()->getWorkspace() should be used.

Same in the following code:

```
'__workspace':
      search:
        elasticSearchMapping:
          type: string
          index: not_analyzed
          include_in_all: false
        indexing: '${node.workspace.name}'
```

I am 95% confident this must be node.context.workspace.name -- but I wonder why nobody noticed that before (weird).

Greets, Sebastian
